

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    build:
      context: ./backend
    image: juanalbertolr/gestordetareas-backend:latest  # Etiqueta para el backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/appFullStackMEAN
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: juanalbertolr/gestordetareas-frontend:latest  # Etiqueta para el frontend
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
